### PR TITLE
Fix f.reach FPs for larger mobs

### PR DESCRIPTION
**Pull request by steviebeenz**
Steal MarkElf's patch 😉

### CODE REVIEW

**Comment by MarkElf** [comment]
That's what they're there for. :)
IDK how to account for smaller/larger slimes so I just took the biggest slime size.

**Comment by terminalsin** [comment]
god be our savior, this only hurts my eyes

**Comment by MarkElf** [comment]
As in it looks like bad coding? Yeah, kinda and there's room for improvement since the check is entirely based on PvE content. I'm working with the framework I was provided with. If you want to rewrite the entire f.reach section, be my guest @terminalsin.

**Comment by terminalsin** [comment]
> 
> 
> As in it looks like bad coding? Yeah, kinda and there's room for improvement since the check is entirely based on PvE content. I'm working with the framework I was provided with. If you want to rewrite the entire f.reach section, be my guest @terminalsin.

Conceptually this is entirely wrong. This isn't how you calculate reach. Reach isn't a magic value which expands on different mobs. Each mob has their own respective boundingbox, and such should be what you account for, not this sheer whatever-the-heck-this-is.

**Comment by MarkElf** [comment]
That's sort of what is being accomplished though. I think there are better ways to do it outside of my knowledge (actually, see below for the section added at least) but the current reach check is saying X mob is Y in size so it has a larger hitbox. As a result, the player can hit the mob('s center) from a farther distance away and it works well enough for PvE and PvP content. Just like the tens of "Aimbot check A-Zs" then are a lot of ways to accomplish the same effect. I wish I could get 3.05 blocks of reach to flag a bit more often without the use of adding a flat additional VL every time the check is flagged (not added in this pull request). I don't spend any time testing other ACs for hours a day though it was fun when beginning to explore them like 6 years ago. Again, if you have some insight or means of defining each mob's respective boundary box, then please do share and contribute rather than complaining which isn't helping anyone so far.

NCP defines the size of mobs elsewhere (Can't remember where) and I suppose it should grab those mob sizes from there which would be cleaner than importing all the bigger mobs and saying for this specific reach check, X mob is Y size.

I disagree with the adjustable/dynamic reach and that's a simple toggle in the configuration. It does seem to be a flat 3 blocks with a tiny bit of additional wiggle room when attacking at a 45-degree angle. The current default is pretty lenient.

**Comment by steviebeenz** [comment]
> > As in it looks like bad coding? Yeah, kinda and there's room for improvement since the check is entirely based on PvE content. I'm working with the framework I was provided with. If you want to rewrite the entire f.reach section, be my guest @terminalsin.
> 
> Conceptually this is entirely wrong. This isn't how you calculate reach. Reach isn't a magic value which expands on different mobs. Each mob has their own respective boundingbox, and such should be what you account for, not this sheer whatever-the-heck-this-is.

This is no cheat plus - not Artemis.
It's meant to be lenient.

This patch isn't the best but it's better than what there is now.

**Comment by MarkElf** [comment]
I don't think this topic has anything to do with strictness. That's related to the config, not the check itself, and the default setting is very lenient. Can the check currently detect ~3.05 reach? Assuming configured right, yes after a while (more on additional VL generation above while 3.1 block detection is reasonably quick). This patch just fixed false positives in f.reach with bigger mobs.

**Comment by xaw3ep** [comment]
Will soon add a ray trace check will do much better than adding magic values to heal the problem.
But anyway, thanks for helping 1.17 update faster. https://github.com/Updated-NoCheatPlus/NoCheatPlus/commit/b789af5665efa38cdf4ba5d115df22e0d8d1ac6a

**Pull request closed without merging**
