### PR TITLE
Fixed updatedncp switchitem bypass

### PR DESCRIPTION
**Pull request by EclipsesDev**
previous one fixes switchitem noslow if it is send constantly, but if it send once + c08 packet, previous fix will not work, so this one should patch it

### CODE REVIEW

**Comment by larryngton2** [comment]
YOU BETRAYED US

**Comment by larryngton2** [comment]
HOW DARE YOU

**Comment by EclipsesDev** [comment]
> HOW DARE YOU

🤫 🧏

**Comment by Lysandr0** [comment]
Thank you :)

**Pull request merged**
